import { AiOutlineShoppingCart } from 'react-icons/ai';
import { FiBarChart, FiCreditCard} from 'react-icons/fi';
import { BsBoxSeam, BsCurrencyDollar, BsShield} from 'react-icons/bs';

import { BiDonateHeart} from 'react-icons/bi';
import { IoMdContacts} from 'react-icons/io';
import { RiContactsLine} from 'react-icons/ri';
import { MdOutlineSupervisorAccount } from 'react-icons/md';
import { HiOutlineRefresh } from 'react-icons/hi';
import { TiTick } from 'react-icons/ti';

export const links = [
    {
      title: 'Панель керування',
      smallTitle: 'Dash',
      links: [
        {
          name: 'Комерція лікарні',
          href: '',
          icon: <BiDonateHeart />,
        },
      ],
    },
  
    {
      title: 'Сторінки',
      smallTitle: 'Pages',
      links: [
        {
          name: 'Активні клієнти',
          href: 'orders',
          icon: <AiOutlineShoppingCart />,
        },
        {
          name: 'Працівники',
          href: 'employees',
          icon: <IoMdContacts />,
        },
        {
          name: 'Історія клієнтів',
          href: 'customers',
          icon: <RiContactsLine />,
        },
      ],
    },
  ];

export const earningData = [
    {
      icon: <MdOutlineSupervisorAccount />,
      amount: '3,354',
      percentage: '-4%',
      title: 'Обслуговано клієнтів',
      iconColor: '#03C9D7',
      iconBg: '#E5FAFB',
      pcColor: 'red',
    },
    {
      icon: <BsBoxSeam />,
      amount: '12,396',
      percentage: '+23%',
      title: 'Послуги що надали',
      iconColor: 'rgb(255, 244, 229)',
      iconBg: 'rgb(254, 201, 15)',
      pcColor: 'green',
    },
    {
      icon: <FiBarChart />,
      amount: '43,395',
      percentage: '+38%',
      title: 'Продажі послуг',
      iconColor: 'rgb(228, 106, 118)',
      iconBg: 'rgb(255, 244, 229)',
  
      pcColor: 'green',
    },
    {
      icon: <HiOutlineRefresh />,
      amount: '3,026',
      percentage: '-12%',
      title: 'Клієнти які повернулися',
      iconColor: 'rgb(0, 194, 146)',
      iconBg: 'rgb(235, 250, 242)',
      pcColor: 'red',
    },
  ];

  export const lineChartData = [
    [
      { x: new Date(2023, 0, 1), y: 21 },
      { x: new Date(2023, 1, 1), y: 24 },
      { x: new Date(2023, 2, 1), y: 36 },
      { x: new Date(2023, 3, 1), y: 38 },
      { x: new Date(2023, 4, 1), y: 54 },
      { x: new Date(2023, 5, 1), y: 57 },
      { x: new Date(2023, 6, 1), y: 70 },
      { x: new Date(2023, 7, 1), y: 24 },
      { x: new Date(2023, 8, 1), y: 36 },
      { x: new Date(2023, 9, 1), y: 38 },
      { x: new Date(2023, 10, 1), y: 54 },
      { x: new Date(2023, 11, 1), y: 57 },
    ],
    [
      { x: new Date(2023, 0, 1), y: 28 },
      { x: new Date(2023, 1, 1), y: 44 },
      { x: new Date(2023, 2, 1), y: 48 },
      { x: new Date(2023, 3, 1), y: 50 },
      { x: new Date(2023, 4, 1), y: 66 },
      { x: new Date(2023, 5, 1), y: 78 },
      { x: new Date(2023, 6, 1), y: 84 },
      { x: new Date(2023, 7, 1), y: 66 },
      { x: new Date(2023, 8, 1), y: 50 },
      { x: new Date(2023, 9, 1), y: 77 },
      { x: new Date(2023, 10, 1), y: 80 },
      { x: new Date(2023, 11, 1), y: 90 },
    ],
  
    [
      { x: new Date(2023, 0, 1), y: 10 },
      { x: new Date(2023, 1, 1), y: 20 },
      { x: new Date(2023, 2, 1), y: 30 },
      { x: new Date(2023, 3, 1), y: 38 },
      { x: new Date(2023, 4, 1), y: 44 },
      { x: new Date(2023, 5, 1), y: 57 },
      { x: new Date(2023, 6, 1), y: 68 },
      { x: new Date(2023, 7, 1), y: 45 },
      { x: new Date(2023, 8, 1), y: 69 },
      { x: new Date(2023, 9, 1), y: 60 },
      { x: new Date(2023, 10, 1), y: 71 },
      { x: new Date(2023, 11, 1), y: 63 },
    ],
  ];


  export const lineCustomSeries = [
    { dataSource: lineChartData[0],
      xName: 'x',
      yName: 'y',
      name: 'Карпюк',
      width: '2',
      marker: { visible: true, width: 10, height: 10 },
      type: 'Line' },
  
    { dataSource: lineChartData[1],
      xName: 'x',
      yName: 'y',
      name: 'Опалько',
      width: '2',
      marker: { visible: true, width: 10, height: 10 },
      type: 'Line' },
  
    { dataSource: lineChartData[2],
      xName: 'x',
      yName: 'y',
      name: 'Войтюк',
      width: '2',
      marker: { visible: true, width: 10, height: 10 },
      type: 'Line' },
  
  ];

  export const LinePrimaryXAxis = {
    valueType: 'DateTime',
    labelFormat: 'y',
    intervalType: 'Days',
    edgeLabelPlacement: 'Shift',
    majorGridLines: { width: 0 },
    background: 'white',
  };

  export const LinePrimaryYAxis = {
    labelFormat: '{value}%',
    rangePadding: 'None',
    minimum: 0,
    maximum: 100,
    interval: 20,
    lineStyle: { width: 0 },
    majorTickLines: { width: 0 },
    minorTickLines: { width: 0 },
  };


  export const recentTransactions = [
    {
      icon: <BsCurrencyDollar />,
      amount: '+₴1.256.550',
      title: 'Отримано від НЦЗУ',
      desc: 'Money Added',
      iconColor: '#03C9D7',
      iconBg: '#E5FAFB',
      pcColor: 'green',
    },
    {
      icon: <BsShield />,
      amount: '-₴120.000',
      desc: 'Money reversed',
      title: 'Закупівля вакцини',
      iconColor: 'rgb(0, 194, 146)',
      iconBg: 'rgb(235, 250, 242)',
      pcColor: 'red',
    },
    {
      icon: <FiCreditCard />,
      amount: '-₴340.000',
      title: 'Зарплати працівникам',
      desc: 'Payment Sent',
      iconColor: 'rgb(255, 244, 229)',
      iconBg: 'rgb(254, 201, 15)',
  
      pcColor: 'red',
    },
    {
      icon: <TiTick />,
      amount: '+₴250.000',
      title: 'Платні послуги',
      desc: 'Money Added',
  
      iconColor: 'rgb(228, 106, 118)',
      iconBg: 'rgb(255, 244, 229)',
      pcColor: 'green',
    },
    {
      icon: <BsCurrencyDollar />,
      amount: '-₴54.000',
      percentage: '+38%',
      title: 'Комунальні послуги',
      desc: 'Payment Sent',
      iconColor: '#03C9D7',
      iconBg: '#E5FAFB',
      pcColor: 'red',
    },
  ];

  export const mockDataContacts = [
    {
      id: 1,
      name: "Jon Snow",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "jonsnow@gmail.com",
      age: 35,
      phone: "(665)121-5454",
      address: "0912 Won Street, Alabama, SY 10001",
      city: "New York",
      zipCode: "10001",
      registrarId: 123512,
    },
    {
      id: 2,
      name: "Cersei Lannister",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "cerseilannister@gmail.com",
      age: 42,
      phone: "(421)314-2288",
      address: "1234 Main Street, New York, NY 10001",
      city: "New York",
      zipCode: "13151",
      registrarId: 123512,
    },
    {
      id: 3,
      name: "Jaime Lannister",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "jaimelannister@gmail.com",
      age: 45,
      phone: "(422)982-6739",
      address: "3333 Want Blvd, Estanza, NAY 42125",
      city: "New York",
      zipCode: "87281",
      registrarId: 4132513,
    },
    {
      id: 4,
      name: "Anya Stark",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "anyastark@gmail.com",
      age: 16,
      phone: "(921)425-6742",
      address: "1514 Main Street, New York, NY 22298",
      city: "New York",
      zipCode: "15551",
      registrarId: 123512,
    },
    {
      id: 5,
      name: "Daenerys Targaryen",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "daenerystargaryen@gmail.com",
      age: 31,
      phone: "(421)445-1189",
      address: "11122 Welping Ave, Tenting, CD 21321",
      city: "Tenting",
      zipCode: "14215",
      registrarId: 123512,
    },
    {
      id: 6,
      name: "Ever Melisandre",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "evermelisandre@gmail.com",
      age: 150,
      phone: "(232)545-6483",
      address: "1234 Canvile Street, Esvazark, NY 10001",
      city: "Esvazark",
      zipCode: "10001",
      registrarId: 123512,
    },
    {
      id: 7,
      name: "Ferrara Clifford",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "ferraraclifford@gmail.com",
      age: 44,
      phone: "(543)124-0123",
      address: "22215 Super Street, Everting, ZO 515234",
      city: "Evertin",
      zipCode: "51523",
      registrarId: 123512,
    },
    {
      id: 8,
      name: "Rossini Frances",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "rossinifrances@gmail.com",
      age: 36,
      phone: "(222)444-5555",
      address: "4123 Ever Blvd, Wentington, AD 142213",
      city: "Esteras",
      zipCode: "44215",
      registrarId: 512315,
    },
    {
      id: 9,
      name: "Harvey Roxie",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "harveyroxie@gmail.com",
      age: 65,
      phone: "(444)555-6239",
      address: "51234 Avery Street, Cantory, ND 212412",
      city: "Colunza",
      zipCode: "111234",
      registrarId: 928397,
    },
    {
      id: 10,
      name: "Enteri Redack",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "enteriredack@gmail.com",
      age: 42,
      phone: "(222)444-5555",
      address: "4123 Easer Blvd, Wentington, AD 142213",
      city: "Esteras",
      zipCode: "44215",
      registrarId: 533215,
    },
    {
      id: 11,
      name: "Steve Goodman",
      data: "21-01-2023",
      time: "10:30",
      reason: "Захворювання",
      email: "stevegoodmane@gmail.com",
      age: 11,
      phone: "(444)555-6239",
      address: "51234 Fiveton Street, CunFory, ND 212412",
      city: "Colunza",
      zipCode: "1234",
      registrarId: 92197,
    },
  ];

  export const mockDataTeam = [
    {
      id: 1,
      name: "Jon Snow",
      email: "jonsnow@gmail.com",
      age: 35,
      phone: "(665)121-5454",
      access: "admin",
    },
    {
      id: 2,
      name: "Cersei Lannister",
      email: "cerseilannister@gmail.com",
      age: 42,
      phone: "(421)314-2288",
      access: "manager",
    },
    {
      id: 3,
      name: "Jaime Lannister",
      email: "jaimelannister@gmail.com",
      age: 45,
      phone: "(422)982-6739",
      access: "user",
    },
    {
      id: 4,
      name: "Anya Stark",
      email: "anyastark@gmail.com",
      age: 16,
      phone: "(921)425-6742",
      access: "admin",
    },
    {
      id: 5,
      name: "Daenerys Targaryen",
      email: "daenerystargaryen@gmail.com",
      age: 31,
      phone: "(421)445-1189",
      access: "user",
    },
    {
      id: 6,
      name: "Ever Melisandre",
      email: "evermelisandre@gmail.com",
      age: 150,
      phone: "(232)545-6483",
      access: "manager",
    },
    {
      id: 7,
      name: "Ferrara Clifford",
      email: "ferraraclifford@gmail.com",
      age: 44,
      phone: "(543)124-0123",
      access: "user",
    },
    {
      id: 8,
      name: "Rossini Frances",
      email: "rossinifrances@gmail.com",
      age: 36,
      phone: "(222)444-5555",
      access: "user",
    },
    {
      id: 9,
      name: "Harvey Roxie",
      email: "harveyroxie@gmail.com",
      age: 65,
      phone: "(444)555-6239",
      access: "admin",
    },
  ];